#!/bin/sh
prg="$(cd $(dirname $0); pwd)/$(basename $0)"       # readlink -f 
pmd="$(cd $(dirname $0); pwd)/desktop_image.py"
lof="$(cd $(dirname $0); pwd)/desktop_image.log"

laconf="$HOME/Library/LaunchAgents/desktop.background.rotate.plist"
name="desktop.background.rotate"
interval=120

usage() {
  cat <<-__EOF
    ciao 
    come sta?
__EOF
}

start() {
  if [ ! -f $laconf ] ; then
    echo "Configuring $name with interval of $interval seconds"
    cat > $laconf <<-____EOF
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>Label</key>
        <string>$name</string>
        <key>ProgramArguments</key>
        <array>
          <string>sh</string>
          <string>-c</string>
          <string>$prg</string>
        </array>
        <key>StartInterval</key>
        <integer>$interval</integer>
      </dict>
      </plist>    
____EOF
  #         <key>RunAtLoad</key>
  #         <true/>
  fi
  rm -f $lof
  echo "Registering $name service" | tee -a $lof
  launchctl list | grep -q "$name"  || launchctl load -w $laconf
}

stop() {
  echo "Unregistering $name service" | tee -a $lof
  launchctl remove $name
  rm -f $laconf  
}

status() {
  launchctl list "$name" 2> /dev/null
  if [ $? -eq 0 ] ; then
    echo "Installed"
  else
    echo "Not installed"
  fi
}

restart() {
  stop
  sleep 2
  start
}

run() {
  pef="$(dirname $0)/.python-version"
  if [ -f $pef ] ; then
    export PYENV_VERSION=$(cat $pef)
  fi
  if [ -f $HOME/.pyenv/shims/python ] ; then
    $HOME/.pyenv/shims/python $pmd 
  else
    python $pmd
  fi
}

cmd="run"
while [ $# -gt 0 ] ; do
case $1 in
-t) 
  interval=$2
  shift 2
  ;;
-h) 
  usage
  shift 1
  exit
  ;;
start|stop|restart|status|run)
  cmd=$1
  shift 1
  ;;
*)
  echo "Unrecognized option $1"
  usage
  exit
esac
done

$cmd
